### ISSUE TITLE
Value stored with SecurePreferences.setValue is wiped after phone reboot

### ISSUE THREAD

**Issue by ExPl0siF** [adorsys/secure-storage-android#41] opened 2019-04-16 10:15 UTC
Dear adorsys

    I have a small problem with your well made encapsulation, when I reboot the Android device (Phillips TV 4.4.4) the key that I have previously stored is wiped ... Do you know why? Is it normal? If it is normal is that possible to make a parameter to set data permanency?

Thank you very much in advance,

ExPL0siF

**Comment by luckyhandler** [comment] 2019-04-16 13:41
Hi @ExPl0siF,
Thanks for reporting this. 
This is not a normal behaviour. Are you sure that you are using Android Api 4.4.4 a.k.a. Api 19?

**Comment by ExPl0siF** [comment] 2019-04-16 14:02
You're welcome. Yes I'am absolutely sure.  It's Android 4.4.4 API 19 Kernel 3.0.36+ and I'm on Phillips 55BDL4050D the build number is FB09.03

I hope it will help you

**Comment by luckyhandler** [comment] 2019-05-31 14:59
@ExPl0siF I actually cannot see why this bug occurs, I need more information about this bug from your side. Please provide the exact error definition:
- Do you get an exception from SecureStorage and if yes, which
- Is the Value you retrieve from SecureStorage simply null?

**Comment by luckyhandler** [comment] 2019-05-31 15:41
Please also make sure that the issue is still occurring with the newest SecureStorage version. We added some improvements to 1.1.0

**Comment by luckyhandler** [comment] 2019-06-10 17:45
I will close this issue as there hasn't been any activity for some time now

**Closed as completed by luckyhandler** 2019-06-10 17:45 UTC
